### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by Asinin3** [Utazukin/Ichaival#9]
On my LG V40 (1440x2960), text for the `Random` and `New` buttons doesn't quite fit in both Portrait and Landscape.
![Capture+_2019-12-30-19-07-55~2](https://user-images.githubusercontent.com/15137035/71574421-8ce1e980-2b38-11ea-8611-85d0e3aa19f5.png)
And the `X` button to close the side-bar when viewing a gallery doesn't work. You have to swipe in order to close the side-bar, which isn't a big deal.
![Capture+_2019-12-30-19-10-07](https://user-images.githubusercontent.com/15137035/71574447-a5520400-2b38-11ea-8df2-f814d2a244f0.png)
If you *do* click on the `X` all that happens is the size of the side-bar and image changes:
![Capture+_2019-12-30-19-10-39](https://user-images.githubusercontent.com/15137035/71574486-cca8d100-2b38-11ea-9c8d-64e31ae008c5.png)

Finally, when the status-bar auto-hides in portrait mode, the space it was taking up does not get used by lchaival, which makes the auto-hide fairly pointless unless you're using landscape, where it does actually work.

I also wish there was a way to stop the navigation bar from randomly hiding as it can be a bit hard to bring it up again, but that's not really an "issue" and more of a request.

**Comment by Utazukin** [comment]
Version 0.7.0 should fix the issue with the status bar space not getting used in portrait mode.  I'll probably add an option to disable the auto-hide or change the timeout in the next version, but tapping the middle of image should bring it back currently.  As for the `X` in the bookmark drawer, it doesn't close the drawer.  It removes all the bookmarks.
I wasn't able to reproduce the issue with the `Random` and `New` text, but I did try changing how that layout is handled in 0.7.0, so that might be better.

**Comment by Asinin3** [comment]
I can confirm you fixed everything, even the `Random` and `New` text. Thanks!
